#!/usr/bin/env bash

# Re-verifies a fixture64 corpus restored from the Actions cache together with the
# reproducibility receipt earned when it was generated: the receipt must describe this
# corpus, and the corpus must still verify against its provenance. A corpus that fails
# here is regenerated by the caller instead of being handed to the benchmark jobs.

set -euo pipefail

if [[ $# -ne 4 ]]; then
  echo "Usage: $0 <webgraph-jmh.jar> <fixture-jar-directory> <prepared-output> <receipt>" >&2
  exit 2
fi

JMH_JAR=$1
FIXTURE_DIR=$2
OUTPUT=$3
RECEIPT=$4

test -f "${JMH_JAR}"
test -d "${FIXTURE_DIR}"
test -f "${OUTPUT}/graphs.tsv"
test -f "${OUTPUT}/fixture-provenance.tsv"
test -f "${RECEIPT}"

sha256_stream() {
  if command -v sha256sum >/dev/null; then
    sha256sum | awk '{print $1}'
  else
    shasum -a 256 | awk '{print $1}'
  fi
}

# actions/cache may restore the graph directories into a different runner workspace.
# Rebind only the location columns; the semantic columns are hashed below.
OUTPUT_ROOT=$(cd "${OUTPUT}" && pwd)
MANIFEST_TMP=$(mktemp)
PROVENANCE_TMP=$(mktemp)
awk -F '\t' -v OFS='\t' -v root="${OUTPUT_ROOT}" \
  '/^#/ { print; next } { $2=root "/" $1; print }' "${OUTPUT}/graphs.tsv" > "${MANIFEST_TMP}"
awk -F '\t' -v OFS='\t' -v root="${OUTPUT_ROOT}" \
  'NR == 1 { print; next } { $19=root "/" $1; print }' \
  "${OUTPUT}/fixture-provenance.tsv" > "${PROVENANCE_TMP}"
mv "${MANIFEST_TMP}" "${OUTPUT}/graphs.tsv"
mv "${PROVENANCE_TMP}" "${OUTPUT}/fixture-provenance.tsv"

test "$(grep -cv '^#' "${OUTPUT}/graphs.tsv")" -eq 64
PROVENANCE_SHA=$(cut -f1-18 "${OUTPUT}/fixture-provenance.tsv" | sha256_stream)
MANIFEST_SHA=$(awk -F '\t' 'BEGIN { OFS="\t" } /^#/ { print; next } { print $1, $3, $4, $5, $6 }' \
  "${OUTPUT}/graphs.tsv" | sha256_stream)
jq -e --arg provenance "${PROVENANCE_SHA}" --arg manifest "${MANIFEST_SHA}" \
  '.passed == true and .firstProvenanceSha256 == $provenance and
   .repeatedProvenanceSha256 == $provenance and
   .firstManifestSemanticSha256 == $manifest and
   .repeatedManifestSemanticSha256 == $manifest' "${RECEIPT}" >/dev/null

find_one() {
  local pattern=$1
  local matches=()
  while IFS= read -r match; do
    matches+=("${match}")
  done < <(find "${FIXTURE_DIR}" -maxdepth 1 -type f -name "${pattern}" -print | sort)
  test "${#matches[@]}" -eq 1
  printf '%s\n' "${matches[0]}"
}

ANDROID_JAR=$(find_one 'android-all-*.jar')
TIKA_JAR=$(find_one 'tika-app-*.jar')
HIVE_JAR=$(find_one 'hive-exec-*.jar')
KOTLIN_JAR=$(find_one 'kotlin-compiler-embeddable-*.jar')
java -Xmx4g \
  -Dandroid.jar.path="${ANDROID_JAR}" \
  -Dtika.jar.path="${TIKA_JAR}" \
  -Dhive.jar.path="${HIVE_JAR}" \
  -Dkotlin.compiler.jar.path="${KOTLIN_JAR}" \
  -cp "${JMH_JAR}" \
  io.johnsonlee.graphite.webgraph.Fixture64GraphPreparation \
  --verify "${OUTPUT}/graphs.tsv" "${OUTPUT}/fixture-provenance.tsv"

echo "Restored fixture64 corpus matches its reproducibility receipt and provenance"
