#!/usr/bin/env python3
"""Compact the saved Java 17 / main Kotlin BMP Char oracle into range data."""
import gzip, pathlib, struct, subprocess
root = pathlib.Path(__file__).resolve().parent
data = gzip.decompress((root / 'java17-char.bin.gz').read_bytes())
rows = []
pos = 0
for cp in range(65536):
    flags, length = data[pos:pos+2]; pos += 2
    title = struct.unpack_from('>' + 'H'*length, data, pos); pos += length*2
    rows.append((flags, title))
assert pos == len(data)
lines = ['// Code generated by testdata/generate-char.py from the Java 17 / main Kotlin oracle; DO NOT EDIT.', 'package javastring', '']
for name, bit in [('charLower', 1), ('charUpper', 2)]:
    ranges = []
    for cp, (flags, _) in enumerate(rows):
        if flags & bit:
            if ranges and ranges[-1][1] == cp-1: ranges[-1][1] = cp
            else: ranges.append([cp, cp])
    lines += ['var '+name+' = [][2]uint16{']
    lines += ['{0x%x, 0x%x},' % tuple(r) for r in ranges]
    lines += ['}', '']
ranges = []; special = []
for cp, (_, title) in enumerate(rows):
    if len(title) != 1:
        special.append((cp, title))
    elif title[0] != cp:
        delta = title[0]-cp
        if ranges and ranges[-1][1] == cp-1 and ranges[-1][2] == delta: ranges[-1][1] = cp
        else: ranges.append([cp, cp, delta])
lines += ['var charTitleRanges = [][3]int32{']
lines += ['{0x%x, 0x%x, %d},' % tuple(r) for r in ranges]
lines += ['}', '', 'var charTitleSpecial = map[uint16]string{']
lines += ['0x%x: "%s",' % (cp, ''.join('\\u%04x' % u for u in title)) for cp, title in special]
lines += ['}', '']
path = root.parent / 'char_generated.go'
path.write_text('\n'.join(lines))
subprocess.run(['gofmt', '-w', str(path)], check=True)
