from pathlib import Path
import hashlib,json
P=Path(__file__).resolve().parent;ROOT=P.parents[4];ORACLE=P.parent.parent/'mapped-cursor-oracle';EXTERNAL=Path('/Users/johnsonlee/.codex/benchmarks/graphite/persisted-work-f0838dda-cursor-focused-v2');MODULE=ROOT/'graphite-server'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
files=['internal/store/main_mapped_cursor.go','internal/store/main_mapped_cursor_test.go','internal/store/main_callsite_index_test.go','internal/store/callsite_index.go','internal/store/main_mapped_work_reader.go','internal/query/main_string_mapped.go','internal/query/ordinary_parallel.go','internal/query/main_mapped_iteration_test.go','internal/query/main_mapped_match.go','internal/query/main_mapped_match_test.go','internal/query/storage_work.go','internal/query/indexed_distinct.go','internal/query/ordinary_cache.go']
inputs=json.loads((EXTERNAL/'module-inputs.json').read_text());source=[]
for name in files:
 h=sha(MODULE/name);assert h==inputs[name]==sha(EXTERNAL/'module'/name);source.append(dict(file=name,sha256=h,equalsTerminalV2Input=True))
raw=json.loads((ORACLE/'main.json').read_text());assert raw==json.loads((ORACLE/'repeat-capture/main.json').read_text())
log=(EXTERNAL/'test.log').read_text();receipt=json.loads((EXTERNAL/'receipt.json').read_text());assert receipt['exitCode']==0 and receipt['inputsUnchanged']
rows=[
('C01','source-only','validateMainMappedRange polls position&1023, so a pre-canceled one-item range starting/ending at1023 completes and publishes. No isolated Go singleton1023 test.',''),
('C02','partial-runtime-and-source','The1023..1024 test proves no required read at1024; no isolated pre-canceled singleton1024 test asserting zero validation callbacks.','TestMainMappedCursorPollsAbsolutePositionBeforeRequiredRead'),
('C03','runtime-equivalent-control','Go synthetic owned range1023..1024 checks required read before the absolute1024 poll and leaves cache empty; adds two binary-search units before the same one-unit validation finally.','TestMainMappedCursorPollsAbsolutePositionBeforeRequiredRead'),
('C04','source-only','Binary search explicitly flushes before reading ends and does not poll request context afterward. No Go test cancels solely in that first search callback and checks successful return.',''),
('C05','source-only','Binary-search rejection flush resets pending and submitPersistentWork preserves original Cause; no dedicated original-cause rejection at the binary-search finally callback in these tests.',''),
('C06','runtime-equivalent-control','Range-finally callback sets context cancellation without throwing and cache publication succeeds; separate corrected owned-offset test proves cold owned orders versus warm per-Advance reads.','TestMainMappedCursorFinallyCancellationPublishesCompletedRange;TestMainMappedWarmCursorReadsEachOrderOnlyOnAdvance'),
('C07','partial-runtime-and-source','Range-finally original callback error leaves cache empty and preserves Cause. Same-store fresh-success retry after that exact failure is not explicitly tested by the cursor test; source permits it.','TestMainMappedCursorFinallyCancellationPublishesCompletedRange;TestMainMappedCursorFinallyFailureOverridesReadFailure'),
('C08','source-only-for-new-cursor','New validation loop reads complete range despite negative/nonmonotone order, flushes, caches false, then skips warm validation. Passing older InvalidConsumesEntireRange test calls MainMappedProjectionRange, not the new MainMappedCursorWithWork route.',''),
('C09','source-only','Same-slot different-key failure cannot publish because err returns before cache lock. Completed invalid validation replaces colliding key. Existing race-loser test injects same-key success, not this collision.',''),
('C10','source-only','Binary-finally cancellation can continue into a nonpoll range because subsequent reads enforce Store lifetime rather than request cancellation; no Go combined binary-interrupt->position1023 control.',''),
('C11','runtime-equivalent-control','Empty range publishes valid certificate before cold empty-orders constructor throws; warm cursor has no orders array and reads current posting/order even when hasCurrent false. Tests use positions0 and buffer-end1025; actual-main control used position1.','TestMainMappedCursorEmptyRangeStillConstructsCurrent')]
coverage=[]
for prefix,status,explanation,tests in rows:
 c=next(c for c in raw['cases']if c['name'].startswith(prefix+'-'));names=tests.split(';')if tests else []
 for name in names:assert '--- PASS: '+name+' 'in log
 coverage.append(dict(mainCase=c['name'],mainOperations=len(c['operations']),status=status,explanation=explanation,passingGoTests=names))
report=dict(scope='Read-only cross-check of frozen actual-main11/19 storage-method evidence against current Go source and existing terminal focused-v2 outputs; no runtime invoked by auditor.',actualMain=dict(file=str(ORACLE/'main.json'),sha256=sha(ORACLE/'main.json'),cases=11,operations=19,fullRepeatEqual=True),goEvidence=dict(directory=str(EXTERNAL),receiptSHA256=sha(EXTERNAL/'receipt.json'),logSHA256=sha(EXTERNAL/'test.log'),exitCode=receipt['exitCode'],sourceFiles=source),coverage=coverage,queryIntegration=dict(passingTests=['TestMainMappedIterationBoundaries/exhaust','TestMainMappedIterationBoundaries/limit','TestMainMappedIterationBoundaries/budget','TestMainMappedIterationBoundaries/cancel','TestMainMappedMatchingRetainedFallback','TestMainMappedContains (28 subcases)'],scope='Actual Go integration/pure controls, not11/19 direct replay and not new actual-main heap-iteration captures.',sourceAgreement=['mainSelectedMappedIDs validates all ranges before returning the sequence; heap uses order then nodeId; consumes every pop including duplicates; flushes before unique yield and at EOF; resumes Advance after a yield; limit prevents resuming an abandoned sequence.','mainMappedStringMatches uses one lookup per unique trigram, first smallest anchor on ties, absolute posting-index1024 polls, actual string reads without incidental request checks, and finally flush.','ordinaryStringKey excludes property and includes transform/op/Java term identity, matching main request-local mapped predicate key.','mainExactCanFill uses charged binary search and posting-end reads, preserving bounds checks and early occurrence return.'],notEstablished=['No dedicated actual-main controls here for trigram-anchor absolute polls, heap1024 poll, multiple distinct node-order merge ties, or exact-fill callback interruption.','No actual-Go replay of this11/19 JSON against the exact34-file oracle fixtures.','ordinaryParallelCandidates raw scan and optional PublishProjectionScan admission/two-pass/identity protocol are outside this cursor oracle; next-captured-publication.md remains unexecuted.','Main optional validation-cache reservation denial is outside these captures. Main permits a mapped view with no range cache; Go currently allocates mainRanges unconditionally, so memory-admission equivalence is not established.']),confirmedBugsInReviewedElevenControls=[],conclusion='No definite new production mismatch found in these11 method controls. Runtime-backed coverage is partial; do not relabel source-only rows as full oracle parity.',performanceMeasurement=False)
(P/'audit.json').write_text(json.dumps(report,indent=2)+'\n');print('Wrote audit',sha(P/'audit.json'))
