from pathlib import Path
import json
r=Path(__file__).resolve().parent
a=json.loads((r/'mapped-candidates.json').read_text())
lines=['# 实际 exact 候选与按 ID 查表的适用边界','', '**本轮量化支持只在密集候选时检验位表，排除了无条件替换。** 这是从真实持久图读取的数据结构规模，不是延迟、CPU、分配或峰值测量。所有优化收益仍待配对与 CI 验证。','', '冻结 main 的 raw DISTINCT 为每个谓词构建 IntOpenHashSet。mapped 精确结果按关键词/transform/mode 复用，但四属性同词仍生成四个 set。需区分：每属性支持集、四属性 used-ID 并集 U、某词在 U 中的实际匹配 A，以及全字符串寻址域 S。不能把单属性支持数或全 S 匹配数当作 A。','', '## 数据与独立复算','', '只读导出冻结 JAR 的 64 张字符串表，保留所有 UTF-16 code unit，合计 2,793,940 个字符串；没有执行图查询。导出前后每份 graph.strings 和冻结 JAR hash 一致。原 CallSite 导出含 5,046,935 节点，四属性唯一数逐图与 sidecar header 对齐。','', '主分析从实际 sidecar 的 trigram postings 复现每词的最短 anchor 和精确匹配，并与四属性 used-ID 并集的穷举结果逐项相等。所有被使用的字符串均为 ASCII；未将全表中的非 ASCII 或未被 CallSite 使用的值混入候选。每个 sidecar 在分析前后完整 SHA 相同。','', '## 若对每个存在候选的图构建一次匹配结构','', '| 查询 | 候选图数 | 原 hash key 数组 payload 合计 | 单 byte/ID 属性位表 payload 合计 | 表不大于 hash 的图数 |','|---|---:|---:|---:|---:|']
for c in a['cases']:
 rs=[x for x in c['perGraph'] if x['hasActualCandidates']]; t=c['allCandidateGraphTotals']; n=sum(x['onePropertyMaskBytePayload']<=x['currentHashKeyArraysPayload'] for x in rs)
 lines.append(f"| {c['id']} | {len(rs)} | {t['currentHashKeyArraysPayload']:,} B | {t['onePropertyMaskBytePayload']:,} B | {n} |")
lines += ['', '上述是完整候选图的结构 payload 总和，不代表本次查询实际构造次数或同时存活量。selected tuple 可行性判断、已知来源与 LIMIT 会避免部分构造。没有把 7.0 MB 与 2.8 MB 的总和差当作实测节省。数组/对象头、对齐、原 exact IntArray、索引及其他状态均未包含。', '', '原 key payload 使用冻结 fastutil 的实际公式：n=max(2,nextPowerOfTwo(ceil(m/0.75)))，key 为 int[n+1]。输入 m 是实际候选 A 的长度；本数据 anchor 无重复 ID，四属性重复建 set 按四份计。', '', '## 单一待检验方向', '', '只在 S 不大于原所有 key 数组 payload 合计时构造一个 byte/ID 属性位表，稀疏候选保留原 hash 路径。旧 dense 和 get/set/read/write 的所有候选图满足，旧 targeted 和其他四词 OR 均不满足。这个边界由现有结构容量导出，未使用查询名、词长或固定基准阈值。', '', '其机制是替换 hash/mix/probe；旧四谓词检查上界仍是四次。保持原 predicate 遍历，不能借此混入固定四属性循环、去池、posting 遍历、selected 顺序或缓存变化。table 中合并的是各谓词完成精确匹配后的属性位；原 fallback 与不支持形状不变。', '', '范围错误必须仍按原 hash probe 处理；构造前预检可拒绝不合法候选。新增预检、容量计算、清零和填表都有成本，不能假定省下 hash 就净赚。取消/预算、异常退出、所有 worker join 和共享只读生命周期须独立检查。', '', '- [实际 anchor 复算](mapped-candidates.json) / [脚本](mapped-candidates.py)', '- [属性支持集原始统计](census.json) / [脚本](census.py)：仅属性支持集，不是 mapped A 长度', '- [独立导出与属性/used-ID 核验](independent-census-audit.md)', '- [字符串导出源码](ExportStrings.java) / [构建和执行凭据](string-export-receipt.json)', '', '字符串完整导出保留于临时目录 `'+str(r)+'`；仓库归档保留源码、hash、分析和审计，完整 24 MB gzip 以归档凭据明确记录位置。无生产代码改动由本报告产生。']
(r/'README.md').write_text('\n'.join(lines)+'\n')
