import io.johnsonlee.graphite.core.*;
import io.johnsonlee.graphite.graph.*;
import io.johnsonlee.graphite.webgraph.*;
import com.google.gson.*;
import java.nio.file.*;
import java.util.*;

/** Zero CallSites and zero trigram postings, generated by actual main. */
public class IndexBoundaryOracle {
 static MethodDescriptor method(String c,String n){return new MethodDescriptor(new TypeDescriptor(c,List.of()),n,List.of(),new TypeDescriptor("void",List.of()));}
 public static void main(String[] args)throws Throwable {
  System.setProperty("graphite.webgraph.prepareCallSiteStringIndexOnLoad","lazy");
  var records=new ArrayList<Object>();
  for(String name:new String[]{"empty","short"}) {
   Path dir=Path.of(args[0],name);Files.createDirectories(dir);
   var b=new DefaultGraph.Builder();
   if(name.equals("short"))b.addNode((CallSiteNode)CallSiteNode.class.getConstructors()[0].newInstance(0,method("a","b"),method("c","d"),Integer.valueOf(1),null,List.of(),null));
   GraphStore.INSTANCE.save(b.build(),dir,3,false);
   var g=GraphStore.INSTANCE.loadMapped(dir);var r=new LinkedHashMap<String,Object>();r.put("fixture",name);
   try {
    r.put("loaded",IndexLifecycleOracle.state(g,dir));
    r.put("prepared",IndexLifecycleOracle.prepare(g));
    r.put("afterPrepare",IndexLifecycleOracle.state(g,dir));
    IndexLifecycleOracle.invoke(g,"clearStringPropertyIndexes");
    r.put("afterClear",IndexLifecycleOracle.state(g,dir));
   }finally{((java.io.Closeable)g).close();}
   records.add(r);
  }
  Files.writeString(Path.of(args[1]),new GsonBuilder().serializeNulls().setPrettyPrinting().create().toJson(records)+"\n");
  System.out.println("Captured 2 main index boundary fixtures; correctness only");
 }
}
