package io.johnsonlee.graphite.cli.c4

internal const val DEFAULT_SYSTEM_BOUNDARY = "(default)"
internal const val SUBJECT_APPLICATION_ID = "system:application"
internal const val SUBJECT_LIBRARY_ID = "system:library"
internal const val SUBJECT_FALLBACK_ID = "system:subject"
internal const val SUBJECT_FALLBACK_NAME = "Subject"
internal const val SOFTWARE_SYSTEM_SCOPE_KEY = "softwareSystemId"
internal const val CONTAINER_SCOPE_KEY = "containerId"
internal const val GRAPHITE_TAG = "Graphite"
internal const val SOFTWARE_SYSTEM_TAG = "Software System"
internal const val CONTAINER_TAG = "Container"
internal const val COMPONENT_TAG = "Component"

internal const val ARTIFACT_ID_PREFIX = "artifact:"
internal const val COMPONENT_ID_PREFIX = "component:"
internal const val CONTAINER_ID_PREFIX = "container:"
internal const val DEPENDENCY_ID_PREFIX = "dependency:"
internal const val DEPENDENCY_LIBRARY_ID_PREFIX = "dependency:library:"
internal const val NAMESPACE_ID_PREFIX = "namespace:"
internal const val RUNTIME_ID_PREFIX = "runtime:"

internal const val GRAPHITE_ARCHITECTURE_TYPE_PROPERTY = "graphite.architectureType"
internal const val GRAPHITE_AVAILABLE_LEVELS_PROPERTY = "graphite.availableLevels"
internal const val GRAPHITE_CONFIDENCE_PROPERTY = "graphite.confidence"
internal const val GRAPHITE_CONTAINER_PROPERTY = "graphite.container"
internal const val GRAPHITE_CONTAINER_ID_PROPERTY = "graphite.containerId"
internal const val GRAPHITE_EVIDENCE_PROPERTY = "graphite.evidence"
internal const val GRAPHITE_KIND_PROPERTY = "graphite.kind"
internal const val GRAPHITE_LEVEL_PROPERTY = "graphite.level"
internal const val GRAPHITE_RELATIONSHIP_KIND_PROPERTY = "graphite.relationshipKind"
internal const val GRAPHITE_RESPONSIBILITY_PROPERTY = "graphite.responsibility"
internal const val GRAPHITE_SOURCE_PROPERTY = "graphite.source"
internal const val GRAPHITE_SYSTEM_BOUNDARY_PROPERTY = "graphite.systemBoundary"
internal const val GRAPHITE_WEIGHT_PROPERTY = "graphite.weight"

internal const val WIRE_AVAILABLE_LEVELS = "availableLevels"
internal const val WIRE_CONTEXT = "context"
internal const val WIRE_DESCRIPTION = "description"
internal const val WIRE_ELEMENTS = "elements"
internal const val WIRE_EXTERNAL_DEPENDENCIES = "externalDependencies"
internal const val WIRE_ID = "id"
internal const val WIRE_KIND = "kind"
internal const val WIRE_LEVEL = "level"
internal const val WIRE_NAME = "name"
internal const val WIRE_RELATIONSHIPS = "relationships"
internal const val WIRE_RESPONSIBILITY = "responsibility"
internal const val WIRE_SKIPPED_REASON = "skippedReason"
internal const val WIRE_SYSTEM_BOUNDARY = "systemBoundary"
internal const val WIRE_TYPE = "type"
internal const val WIRE_WEIGHT = "weight"

internal const val WIRE_ACTOR = "actor"
internal const val WIRE_APPLICATION = "application"
internal const val WIRE_APPLICATION_RUNTIME = "application-runtime"
internal const val WIRE_APPLICATION_SERVICE = "application-service"
internal const val WIRE_CAPABILITY = "capability"
internal const val WIRE_COORDINATION = "coordination"
internal const val WIRE_DOMAIN_COMPONENT = "domain-component"
internal const val WIRE_ENTRYPOINT = "entrypoint"
internal const val WIRE_EXTERNAL_SYSTEM = "external-system"
internal const val WIRE_INTEGRATION = "integration"
internal const val WIRE_INTERFACE = "interface"
internal const val WIRE_LIBRARY = "library"
internal const val WIRE_ORCHESTRATOR = "orchestrator"
internal const val WIRE_RUNTIME = "runtime"
internal const val WIRE_SHARED_CAPABILITY = "shared-capability"
