from pathlib import Path
import json,hashlib,shutil,tarfile,re
r=Path(__file__).resolve().parent;a=Path('/tmp/graphite-atom-attempt19-evidence');H=lambda b:hashlib.sha256(b).hexdigest()
inv=json.loads((r/'candidate-inputs.json').read_text())
for n,v in inv.items():assert H((r/'combined/candidate'/n).read_bytes())==v['sha256'],n
(r/'final-source-verification.json').write_text(json.dumps({'inputs':len(inv),'module':2439,'external':59,'allExactAuthorAndPostTest':True,'base':(r/'base.txt').read_text().strip()},indent=2)+'\n')
with tarfile.open(r/'candidate-source.tar.gz','w:gz') as t:
 for n in sorted(inv):t.add(r/'combined/candidate'/n,arcname=n,recursive=False)
shutil.copytree(a/'base-output',r/'baseline-output',dirs_exist_ok=True)
(r/'author-initial').mkdir(exist_ok=True)
for n in ['base-initial-quadratic-command.json','base-initial-quadratic-full-race.log','initial-quadratic-cancellation-test.go','initial-quadratic-failure.json']:shutil.copy2(a/n,r/'author-initial'/n)
(r/'existing-main').mkdir(exist_ok=True)
for i in range(3):shutil.copy2(Path('/tmp/graphite-projection-context-attempt17-evidence/existing-main')/f'rolling-main-{i}.json',r/'existing-main'/f'rolling-main-{i}.json')
log=(r/'original-matcher-overlay.log').read_text();assert '\nPASS\n' in log and 'no tests to run' not in log
names=re.findall(r'^--- PASS: (\S+)',log,re.M);assert len(names)==3;sub=len(re.findall(r'^    --- PASS:',log,re.M));assert sub==60
(r/'named-executions.json').write_text(json.dumps({'originalEvalOnlyOverlayNames':names,'cancellationSubcases':sub,'longCheckScheduleLines':[s.strip() for s in log.splitlines() if 'long-input original checks=' in s],'operandCandidateAndOriginal':66,'realScheduleTest':'TestReviewG8RetainedAllowedSchedule','scheduleControlAndBarrierPassed':True},indent=2)+'\n')
(r/'commands.json').write_text(json.dumps({'base':(r/'base.txt').read_text().strip(),'go':'go1.22.0 darwin/arm64','cwd':str(r/'combined/candidate/graphite-server'),'commands':[{'argv':['go','test','-race','-count=1','./...'],'env':{'INDEXED_DISTINCT_OUTPUT':str(r/'output/original-corpus'),'ORDINARY_HISTORY_OUTPUT':str(r/'output/history')},'log':'module-race.log','exit':0},{'argv':['go','vet','./...'],'log':'module-vet.log','exit':0},{'argv':['go','test','-race','-v','-count=1','-overlay='+str(r/'original-eval-overlay.json'),'./internal/query','-run','^TestDistinctAtomPredicate'],'log':'original-matcher-overlay.log','exit':0},{'cwd':str(r/'review-module'),'argv':['go','test','-race','-v','-count=1','./internal/query','-run','^TestReviewStringPredicateOperandOrder$'],'env':{'REVIEW_OPERAND_OUTPUT':str(r/'operand-candidate.json')},'log':'operand-candidate.log','exit':0},{'cwd':str(r/'review-module'),'argv':['go','test','-race','-v','-count=1','-overlay='+str(r/'review-original-eval-overlay.json'),'./internal/query','-run','^TestReviewStringPredicateOperandOrder$'],'env':{'REVIEW_OPERAND_OUTPUT':str(r/'operand-original.json')},'log':'operand-original.log','exit':0},{'cwd':str(r/'review-module'),'argv':['go','vet','./internal/query'],'log':'review-vet.log','exit':0},{'cwd':str(r/'combined/base/graphite-server'),'argv':['go','test','-race','-v','-count=1','./internal/query','-run','^TestOrdinaryProjectionRollingSourcesMain$'],'runs':[0,1,2],'outputPattern':'original-rolling-{i}','allExit':0},{'cwd':str(r/'schedule-g8/module'),'argv':['go','test','-race','-v','-count=1','./internal/query','-run','^TestReviewG8RetainedAllowedSchedule$'],'env':{'G8_SCHEDULE_OUTPUT':str(r/'schedule-g8/output')},'log':'schedule-g8/run.log','exit':0},{'cwd':str(r/'schedule-g8/module'),'argv':['go','vet','./internal/query'],'log':'schedule-g8/vet.log','exit':0},{'argv':['python3','compare_outputs.py'],'log':'strict-comparison-failure.log','exit':1},{'argv':['python3','final_verification.py'],'exit':0}], 'noJVMHTTP64PerformanceOrCommit':True},indent=2)+'\n')
(r/'README.md').write_text('''# Independent Attempt19 review

Bounded verdict: no new production correctness blocker found. Full module race/vet and complete public-response comparisons pass. The original strict state comparison still fails and is preserved; two new retained leaves have a separate exact-original allowed-schedule proof, not a blanket normalization or frequency claim.

## Inputs and byte proofs

Base39eedb33cec988f2b40ccf8086514adcb81cab4f contains A18 but no lazyedge/relationship blocks. An independent git archive supplied2437 module+59 external references. Author manifest46e5e952f4323e7a31e766636b0c7015837f8ce1b1f916ac2f82237e4a863ad7 verified all275 files. Exact patch dfadcbdadfc32ff638bfcce71b0774e60cdf60241e09e710d2c1512cb60c0dfc applies cleanly. Candidate2439 module+59 external inputs exactly equal author candidate-inputs.json and were rehashed after tests.

Only eval.go, indexed_distinct.go, new string_predicate.go and new distinct_atom_predicate_test.go differ. Independent proof checks the matching block byte-for-byte except indentation/operator parameter, all other eval bytes except the now-unused import, the original atom reference, unchanged nonstring/lower prefix and fallback return, and unchanged indexed file outside this helper. No source/cursor/Store/context/task/cache/registry changes are included.

## Independent cancellation and operand evidence

The atom fast path replaces two Literal evaluations with exactly two check calls. Those evaluations had no behavior beyond check and returning their already-evaluated string values. javaCase stays before them, nonstring values still return before checks, and non-specialized operators continue through binary. The shared six-operator UTF8/UTF16 matching body preserves its original checks and NOT semantics.

Final new tests were run with original eval.go overlaid on its existing canonical path while retaining candidate distinctAtomMatches and new stringPredicate. Thus the reference invokes the original inline matcher, not the extracted body used by the candidate atom. All three named tests and60 cancellation subcases actually ran and passed. Long lower input observes6000 case checks: specialized ops6004 total, equality/unsupported6002. The recorded schedule includes case first/middle/end, both literals, matcher entry/exit where present and the first beyond-completion checkpoint. Short samples remain exhaustive. Real WithCancel states and exact observed check counts are compared. This is correctness scheduling, not a benchmark.

An independently added test emits66 complete type/null/right-error/check records. A nonstring left (including a named Go string) avoids evaluating the throwing right operand and uses one check; a string left with nonstring right uses two checks without entering matching. A string left preserves the actual right ClassCastException. All six public operators are covered; private atom named-string rejection remains before cancellation. Candidate and original-eval overlays match every record. The added test lives only in review-module; both named runs and query vet pass.

Full module race/vet pass, including existing actual-JVM predicate oracles and all query/store/Close/task coverage. No JVM or HTTP process was launched by this review. The author's initial180s timeout came from exhaustive quadratic long-input test scheduling before production changes; initial source/log/command/failure metadata are copied here and the complete partial output remains in verified author evidence. Final candidate tests use the bounded schedule unchanged.

## Complete outputs and retained-state investigation

All76 expected captures remain present. Raw equality is73/76. Seventy-one changed mappedView booleans occur only in exact documented paths on40-source histories. Two additional leaves are rolling case8 targets[0].after[8].retained and targets[1].before[8].retained, author-base true versus this candidate false. No public response changes occur. Original1048 remains1044 with the same four F cases. B595 complete JSON-value responses and53 ordered design traces pass, including the explicit trace-count assertion. Existing166 number spellings remain recorded; this is not byte equality to main numbers.

The strict verifier still rejects those retained leaves; its script and failure log are unchanged. Three bounded exact-original39 rolling runs all observed g8=true, and all raw results are retained. They do not establish g8=false under natural scheduling; no further random retries were used. Previously frozen main captures at exactly this case/source show true,false,false, with full response equality.

The new schedule-g8 experiment uses exact original39 code, not A19, and directly proves the source mapping. Ordinary projection handles g0 as balanced leading source, then count39 tasks call sources[i+1]; task7 is g8. The sole inserted line defers a scheduling hook immediately before the original task(local,i) invocation. It delays task7 until that existing child's Done closes; it never cancels a context, changes inputs, reads/writes graph state, replaces results or skips original task execution. The original successful LIMIT path cancels and joins the suffix. Removing the one line restores original indexed_distinct.go bytes; all2436 other original module files remain identical. Two added files are test instrumentation only and are not in the candidate archive or patch.

One controlled run and an inactive-hook control both pass actual named race tests and query vet. The controlled trace is child-live entry, scheduler-child-canceled, original-source-task-returned-canceled. Parent remains live, watchdog never fires, g8 is unretained immediately after query0 and before query1, and all three actual ExecuteCross responses equal main. Subsequent queries and Store Close complete after task join. This is an allowed interleaving where g8's launched goroutine progresses to its source only after another task reaches LIMIT. It explains reachability, not natural frequency or equivalent distributions. final_verification.py permits only these two exact retained coordinates after checking the separate proof; the original strict comparison is not rewritten.

All production files stayed frozen. No root/provider/old-freeze edits, commits,64 runs or performance measurements occurred. A future paired real-data run must independently establish cost changes; these finite corpora do not claim100% language parity.
''')
files={str(p.relative_to(r)):{'sha256':H(p.read_bytes()),'bytes':p.stat().st_size} for p in sorted(r.rglob('*')) if p.is_file() and p.relative_to(r).parts[0] not in {'combined','review-module'} and not str(p.relative_to(r)).startswith('schedule-g8/module/') and p.name!='manifest.json'}
(r/'manifest.json').write_text(json.dumps({'base':(r/'base.txt').read_text().strip(),'scope':'Independent A19; exact original-g8 schedule proof separate from candidate','files':files},indent=2)+'\n')
for n in ['manifest.json','candidate-inputs.json','candidate-source.tar.gz','attempt19.patch']:print(n,H((r/n).read_bytes()))
print('files',len(files))
