import com.google.protobuf.gradle.id

description = "Graphite IR - the protobuf Graph IR a language frontend hands to the backend, and its reader"

plugins {
    id("io.johnsonlee.sonatype-publish-plugin")
    id("org.jetbrains.kotlinx.kover") version "0.9.1"
    id("com.google.protobuf") version "0.9.4"
}

// The schema lives at the repository root so every frontend (Kotlin, Swift, ...) reads
// one file; the generated Java classes are this module's.
sourceSets {
    main {
        proto {
            srcDir(rootProject.file("ir"))
        }
    }
}

protobuf {
    protoc {
        artifact = libs.protobuf.protoc.get().toString()
    }
}

kover {
    reports {
        filters {
            excludes {
                // Generated by protoc.
                packages("io.johnsonlee.graphite.ir.v1")
            }
        }
    }
}

dependencies {
    api(project(":core"))
    api(libs.protobuf.java)
}
