#!/usr/bin/env python3
"""Extract pinned Java 17 Unicode casing/whitespace tables for native execution."""
import json,pathlib,subprocess,sys,tempfile
root=pathlib.Path(__file__).resolve().parent
with tempfile.TemporaryDirectory() as tmp:
 subprocess.run(['javac','-cp',sys.argv[1],'-d',tmp,str(root/'GenerateJavaUnicode.java')],check=True)
 data=json.loads(subprocess.check_output(['java','--add-opens=java.base/java.lang=ALL-UNNAMED','--add-opens=java.base/sun.text=ALL-UNNAMED','-Dfile.encoding=UTF-8','-cp',tmp+':'+sys.argv[1],'GenerateJavaUnicode'],text=True))
lines=['// Code generated by testdata/generate-java-unicode.py from Java 17.0.18; DO NOT EDIT.','package query','']
for name in ['lower','upper']:
 lines+=['var java'+name.title()+' = map[rune]string{']
 for code,value in data[name].items():lines.append(code+':'+json.dumps(value,ensure_ascii=False)+',')
 lines+=['}','']
for name in ['whitespace','cased','ignorable']:
 lines+=['var java'+name.title()+' = map[rune]bool{']
 for cp in data[name]:lines.append(str(cp)+':true,')
 lines+=['}','']
lines += ['var javaDigits = map[rune]int{']
for code,value in data['digits'].items():lines.append(code+':'+str(value)+',')
lines += ['}','']
for key,typ in [('wordCategories','[][2]int'),('stateTable','[]int'),('endStates','[]bool'),('lookaheadStates','[]bool')]:
 lines += ['var javaWord'+key[0].upper()+key[1:]+' = '+typ+'{']
 for value in data[key]:
  if isinstance(value,list):lines.append('{'+','.join(str(v) for v in value)+'},')
  else:lines.append(str(value).lower()+',')
 lines += ['}','']
lines += ['const javaWordNumCategories = '+str(data['numCategories'])]
path=root.parent/'java_unicode_generated.go' ;path.write_text('\n'.join(lines))
subprocess.run(['gofmt','-w',str(path)],check=True)
