build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: true

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 18
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 120
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 10
  NestedBlockDepth:
    active: true
    threshold: 4
  TooManyFunctions:
    active: true
    thresholdInFiles: 25
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20

style:
  active: true
  ForbiddenComment:
    active: true
  MagicNumber:
    active: true
    ignoreAnnotation: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreConstantDeclaration: true
    ignoreEnums: true
    ignoreHashCodeFunction: true
    ignoreNamedArgument: true
    ignoreNumbers:
      - "-1"
      - "0"
      - "1"
      - "2"
  MaxLineLength:
    active: true
    excludeImportStatements: true
    excludePackageStatements: true
    maxLineLength: 140
